import "./globals.css";
import { Roboto } from "next/font/google";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Home page",
	description: "Generated by NextJS",
	keywords: "crypto, bitcoin, trade,",
	creator: "vimek patel",
	publisher: "vimek patel",
};

const roboto = Roboto({
	subsets: ["latin"],
	weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
	display: "swap",
});

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={roboto.className}>{children}</body>
		</html>
	);
}
